### PR TITLE
fix: button horizontal

### PR DESCRIPTION
**Pull request by jobmbay**

### CODE REVIEW

**Comment by jobmbay** [comment]
fix my radion button after fork to fieldify/antd

**Review by mykiimike — APPROVED** [review]
LGTM !

**Comment by mykiimike** [comment]
Next time please donc provide the build of the app in the library, we will provide it at release time

**Comment by jobmbay** [comment]
Ok I get the point.

Le dim. 26 juil. 2020 à 07:34, Michael VERGOZ <notifications@github.com> a
écrit :

**Pull request merged**
